entities:
  - id: default
    name: "Default"
    budget: null
    budgetPeriod: null
    aliases: []
    active: true
    notifyOnOverBudget: false
  - id: marketing
    name: "Marketing"
    budget: 5000
    budgetPeriod: monthly
    aliases: ["@marketing","marketing"]
    active: true
    notifyOnOverBudget: true
